export const FETCH_TEAM_REQUEST = 'FETCH_TEAM_REQUEST'
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS'
export const FETCH_TEAM_FAILURE = 'FETCH_TEAM_FAILURE'
export const FETCH_BUDDY_SUBSCRIBE_CHANNEL = 'FETCH_BUDDY_SUBSCRIBE_CHANNEL'